---
title: "Team"
author: "Guang Yi Lim"
date: "March 28, 2019"
output: html_document
---
## Names: Colin Brown and Guang Yi Lim
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Loading data
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
defense <-read_excel('cyclonesFootball2018.xlsx',sheet ='Defensive')
offense <-read_excel('cyclonesFootball2018.xlsx',sheet ='Offensive')
bio <- read_excel('cyclonesFootball2018.xlsx',sheet ='Biography')

```
Cleaning data
```{r}
defense$Name <-as.factor(defense$Name)
defense$Opponent_Opponent <-as.factor(defense$Opponent_Opponent)
names(defense)[2] <-'Opponent'
defenseClean<- defense %>% mutate_if(is.character,as.numeric)


offense$Name <- as.factor(offense$Name)
offense$Opponent_Opponent <- as.factor(offense$Opponent_Opponent)
names(offense)[2] <-'Opponent'
offenseClean <- offense %>% mutate_if(is.character,as.numeric)


bio$Name <-as.factor(bio$Name)
bio$Weight <-as.numeric(bio$Weight)
str(bio)
bioClean <- bio %>% separate(Height, into = c("Feet","Inches") )%>% mutate_at(c("Feet","Inches"),as.numeric)

str(defenseClean)
str(offenseClean)
str(bioClean)

```
<br/>Tidying (1)
```{r}
defenseClean %>% gather(key =Statistics  ,value = Count ,3:11)%>%
  ggplot(aes(x =Count,fill = Statistics))+geom_histogram(binwidth =1)+facet_wrap(~Statistics,scales = "free")

```
<br/>Based on the graph, Turnover_FF, Turnover_FR, and Turnover_INT are rare as only 1 count of each is recorded
```{r}
def_Spread <- defenseClean %>% select(Name,Opponent,Tackles_Solo) %>%
  filter(Opponent == 'West Virginia'| Opponent == 'Kansas State')%>%
  spread(Opponent,Tackles_Solo) %>%
  mutate_all(funs(replace(., is.na(.), 0))) 
ggplot(def_Spread,aes(x = `West Virginia`,y= `Kansas State`,color = Name,size =5))+geom_point()+xlab("West Virginia")+ylab("Kansas State")+ggtitle("Defense Against Kansas State and West Virginia")

```
<br/>Based on the plot, ISU had a better defense againsts Kansas State as the number of solo tackles were higher
<br/>Tidying(2)
```{r}
bioClean <- bioClean %>% separate(Hometown,into = c("City","State"),sep =', ')
head(bioClean)
bioClean_Count <- bioClean %>% group_by(State) %>% summarize(count = n())
bioClean_Count[order(-bioClean_Count$count),]
```
Joining Data Frames
```{r}
offenseJoin <- left_join(offenseClean,bioClean ,by = "Name")
recieve <- offenseJoin %>% filter(!is.na(offenseJoin$Receiving_YDS))
ggplot(recieve,aes(x =Weight,y = Receiving_YDS,color = Name))+geom_point()
recieve <- recieve %>% filter(Name != 'Butler, Hakeem')
ggplot(recieve,aes(x =Weight,y= Receiving_YDS,color =Name))+geom_point()
# There does not seem to be a clear relationship between weight and receiving yards. The amount of receiving yards peaks around weight of 225 lbs for an individual player.

# By looking at the joined offense and biography data, we want to know which players and which positions scored the most touchdowns. Looking at the bar plot below, the Running Back position had the highest frequency of touchdowns, with Montgomery making the most touchdowns.
TD <- offenseJoin %>% select(Name,Position,Receiving_TD,Rushing_TD) %>% 
  group_by(Name) %>%
  filter(!is.na(Position))%>%
  mutate_all(funs(replace(., is.na(.), 0))) %>%
  mutate( total_TD = Receiving_TD+Rushing_TD)

ggplot(TD, aes(x = total_TD,fill = Name)) +geom_bar()+coord_flip()+facet_wrap(~Position) + xlab("Frequency") + ylab("Number of Touchdowns in a Game") + ggtitle("Touchdowns per Game Across Positions and Players")


```



